### ISSUE TITLE
Rendering problem

### ISSUE THREAD

**Issue by ctag-fh-kiel** [mruby-zest/mruby-zest#2]
Hi, I have built zyn-fusion on ARM. Strangely the UI rendering is utterly slow. When I start zynsubaddfx it takes a very long time until the UI appears. Once it appeared, the rendering is very slow, i.e. reaction to interaction events... I set the FPS environment variables both to 20, without any impact...

Any advice?

**Comment by fundamental** [comment]
Is anything output to the console? (I might have checked in a debug flag by mistake)

Numerically, how slow is slow in rough FPS?

Is it equally slow for clicks/drags/keyboard events?

What is the CPU load generated by the program?

Is it a consistent low framerate situation or does it stutter?

Is the slowness a latency from event sort of issue or is it just low framerate?

Have you made any changes to the source?

Is this slowness present when launching the zyn-fusion binary and not running zynaddsubfx?

**Comment by ctag-fh-kiel** [comment]
Console output is below.
UI starts showing after about 20-30s, then it reacts with 0.5 fps or slower. Can't check if reaction to different event has different behaviour, as it is to slow to notice.

When starting zyn-fusion executable there is almost 100% CPU load.
When starting zynaddsubfx, load is 100% for fusion, 50% for zyn (it's a dual core Odroid U3).
It is a consistent low frame-rate situation, both with zynsubaddfx and zyn-fusion executable.

Screen resolution is 1024x600 set with custom xrandr setting.

I didn't make any changes to the sources. I tried with optimized compiler flags for CPU but no difference.

Log:
Sample Rate = 		44100
Sound Buffer Size = 	256 samples
Internal latency = 	5.8 ms
ADsynth Oscil.Size = 	1024 samples
lo server running on 11426
[INFO] Nio::start()
Starting Audio: JACK
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jackdmp 1.9.10
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2013 Grame.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Failed to connect to session bus for device reservation Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection 
Audio device hw:0 cannot be acquired...
Cannot initialize driver
JackServer::Open failed with -1
Failed to open server
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Error, failed to open jack client on server:  status 17
Error, NULL jackClient through Start()
ERROR: The default audio output failed to open!
Starting MIDI: ALSA
MIDI Started
[INFO] exec-after-init
[INFO] startup OSC
[INFO] UI calbacks
[INFO] OSC replay
[INFO] auto_save setup
[INFO] NSM Stuff
[INFO] LASH Stuff
[INFO] Launching Zyn-Fusion...
[INFO] Main Loop...
Info, alsa midi port connected
Time for a fast load is 12.807ms load(0.019) class(0.004) spawn(12.784)...
making reverse graph[1089]<6.65 ms>
[INFO] UV UDP Stopped
[INFO] UV Loop Stopped
[INFO:Zyn] setup_pugl()
[INFO:Zyn] zest_tick()
[INFO:Zyn] zest_open()
[INFO:Zyn] Found Assets at ./
[INFO:Zyn] Starting Zyn-Fusion
[INFO:Zyn] Thanks for supporting the developement of this project
[INFO:Zyn] Creating MRuby Interpreter...
[debug] parsing json file
[debug] json parsed succesfully
[INFO:Zyn] zest_setup()
[DEBUG:Zyn] setting up animation fps
[INFO:Zyn] zest_close()
[INFO] Closing MRuby Application...
[INFO:Zyn] Destroying pugl view

**Comment by fundamental** [comment]
Framerate of a fullscreen glxgears instance?

**Comment by ctag-fh-kiel** [comment]
Dunno?

**Comment by fundamental** [comment]
If you run the program 'glxgears' from a terminal it will periodically (once per second IIRC) print out the current framerate. Could you install 'glxgears' if it isn't installed on your system, run the program from a terminal, resize the GL window to be fullscreen, wait a few seconds, and then post here what framerate glxgears has as output to the terminal?

**Comment by ctag-fh-kiel** [comment]
28 to 29 fps...

**Comment by fundamental** [comment]
Ok, so glxgears indicates that the GL implementation on your system should be usable. The "fast load" time in the above output indicates that your CPU speed should be plenty, so right now I don't know exactly what's chewing up all of your compute time. 

Are you familiar with using valgrind's callgrind for profiling? If so, could you try to identify what general region of code is eating up the compute time. Once the general cause is located I should be able to point out some of the other internal profiling tools (which are usually turned off to avoid overhead).

**Comment by ctag-fh-kiel** [comment]
No idea about callgrind... can you point at a tutorial or how-to? Do I need to build fusion in debug mode? 
I will check it out... 
Framerate with glxgears has settled around 29.9 fps...

**Comment by fundamental** [comment]
You should be able to go to the mruby-zest-build repo and run "make setup && make builddep && make && make callgrind". After the application displays the first rendering you close the window and then run "kcachegrind callgrind.out.THEPIDNUMBER" That will provide you with more info on the distribution of compute time.

I don't know of a tutorial to recommend, so here's a link to the kcachegrind docs as that's the more complex part IMO: http://kcachegrind.sourceforge.net/html/Documentation.html

**Comment by ctag-fh-kiel** [comment]
I have been able to run callgrind, however kcachegrind doesn't seem to work on the Lubuntu distro the SBC runs. Do you have a chance to have a peek at the profiler results?
3042 is with valgrind --tool=calgrind zyn-fusion, 3132 is with make callgrind in mruby-zest-build directory

[ProfilerFiles.zip](https://github.com/mruby-zest/mruby-zest/files/1653361/ProfilerFiles.zip)

**Comment by fundamental** [comment]
I'm not at my normal machine, so this analysis might be premature, but it looks like a lot of time appears to be spent in a GL library with a name which looks like it might be doing software rendering (i.e. not accelerated with the GPU). Thinking about it, that's not too unusual given that mruby-zest is using OpenGL 2.1+ rather than OpenGLES 2+. 

I'm not sure if this will work or not, but I'd recommend changing MRUBY_NANOVG_GL2 to MRUBY_NANOVG_GLES2 in build_config.rb and remove the 'error "Tell the maintainer of mruby-zest he's an idiot"' line in nvg_impl.h, then rebuild to see if it makes any difference ( "make && make run" ).
This in theory would modify the core nanovg shader enough to make things work smoothly, though additional changes might be needed in the PUGL setup as well as some of the framebuffer handling code.

**Comment by ctag-fh-kiel** [comment]
Tried to compile with your settings, getting a compile error, seems that GLES2 isn't fully supported?
Thx much for all your help! Your reasoning in the previous post makes sense. Any idea on this:

cd src/osc-bridge    && CFLAGS="-I ../../deps/libuv-v1.9.1/include -mfloat-abi=hard -march=armv7-a -mfpu=vfpv3-d16 -mtune=cortex-a9" make lib
make[1]: Entering directory `/root/zyn3/mruby-zest-build/src/osc-bridge'
cc -I ../../deps/libuv-v1.9.1/include -mfloat-abi=hard -march=armv7-a -mfpu=vfpv3-d16 -mtune=cortex-a9 -std=gnu99 -Wall -Wextra -I . -O3 -g -fPIC -c src/bridge.c src/cache.c src/parse-schema.c src/schema.c rtosc/rtosc.c
src/bridge.c: In function ‘br_get_schema’:
src/bridge.c:449:10: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(json, 1, len, f);
          ^
ar rcs libosc-bridge.a bridge.o cache.o parse-schema.o schema.o rtosc.o
make[1]: Leaving directory `/root/zyn3/mruby-zest-build/src/osc-bridge'
cd mruby             && MRUBY_CONFIG=../build_config.rb rake
Environment is:

false
CC    ../deps/mruby-nanovg/src/nvg_impl.c -> build/host/mrbgems/mruby-nanovg/src/nvg_impl.o
In file included from /root/zyn3/mruby-zest-build/deps/mruby-nanovg/src/nvg_impl.c:16:0:
/root/zyn3/mruby-zest-build/mruby/../deps/nanovg/src/nanovg_gl.h: In function ‘glnvg__renderCreateTexture’:
/root/zyn3/mruby-zest-build/mruby/../deps/nanovg/src/nanovg_gl.h:768:3: error: implicit declaration of function ‘glGenerateMipmap’ [-Werror=implicit-function-declaration]
   glGenerateMipmap(GL_TEXTURE_2D);
   ^
cc1: some warnings being treated as errors
In file included from /root/zyn3/mruby-zest-build/deps/mruby-nanovg/src/nvg_impl.c:16:0:
/root/zyn3/mruby-zest-build/mruby/../deps/nanovg/src/nanovg_gl.h: In function ‘glnvg__renderCreateTexture’:
/root/zyn3/mruby-zest-build/mruby/../deps/nanovg/src/nanovg_gl.h:768:3: error: implicit declaration of function ‘glGenerateMipmap’ [-Werror=implicit-function-declaration]
   glGenerateMipmap(GL_TEXTURE_2D);
   ^
cc1: some warnings being treated as errors
rake aborted!
Command failed with status (1): [gcc -g -std=gnu99 -O3 -Wall -Werror-implic...]
/root/zyn3/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:31:in `_run'
/root/zyn3/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:36:in `rescue in _run'
/root/zyn3/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:32:in `_run'
/root/zyn3/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:89:in `run'
/root/zyn3/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:113:in `block (2 levels) in define_rules'
Tasks: TOP => default => all => /root/zyn3/mruby-zest-build/mruby/build/host/lib/libmruby.flags.mak => /root/zyn3/mruby-zest-build/mruby/build/host/lib/libmruby.a => /root/zyn3/mruby-zest-build/mruby/build/host/mrbgems/mruby-nanovg/src/nvg_impl.o
(See full trace by running task with --trace)
make: *** [all] Error 1

**Comment by fundamental** [comment]
Ok, I've had a chance to look at one of the traces via kcachgrind. It shows that 95% of the execution time was spent in glnvg_setUniforms(). The only way I would expect that code to take that much time there is if it was a pure software renderer.

> seems that GLES2 isn't fully supported?

Rendering is mostly done via nanovg which *does* fully support GL2/GL3/GLES2/GLES3. The glue code in the rest of the mruby-zest framework however hasn't been fully tested with anything other than GL2 (well, it technically was initially written for GL3 and then thoroughly ported/tested for GL2, but that's beside the point).

Since I don't have a GLES2 device setup you'll have to do a bit of hacking to get it working, but if the error that you've linked is the only one then it should be an easy enough fix:

gl_core* in https://github.com/mruby-zest/mruby-nanovg/tree/master/src loads all the openGL functions needed for normal operations.
That header is autogenerated via glloadgen https://bitbucket.org/alfonse/glloadgen/wiki/Home 

I personally would just hack in glGenerateMipmap into the loader header and c file, though regenerating the GL2.1 core profile + framebuffer extension + whatever extension gets you glGenerateMipmap is a possibility. Once you have glGenerateMipmap in there then the GUI should compile with OpenGLES which in theory should bypass the software renderer.

There is the possibility that something needs to be configured on your ARM device to get hardware acceleration working, but seeing as glxgears runs at a reasonable pace it looks like the software renderer isn't the only option.

**Comment by ctag-fh-kiel** [comment]
Thx much, am busy atm, but will try asap and let you know...

**Comment by ctag-fh-kiel** [comment]
I regenerated the headers with:
lua LoadGen.lua -spec=gl -version=2.1 -profile=core core.3.2 -exts GL_EXT_framebuffer_sRGB GL_EXT_framebuffer_object GL_ARB_framebuffer_object

I had to change in gem.c 
int nvglCreateImageFromHandleGL2(NVGcontext* ctx, GLuint textureId, int w, int h, int imageFlags);
to
int nvglCreateImageFromHandleGLES2(NVGcontext* ctx, GLuint textureId, int w, int h, int imageFlags);
 
However when I execute "make run" I get these errors now, it seems somehow to want GLES1 instead of 2, any ideas?
./zest osc.udp://127.0.0.1:1337
trace:
        [0] /root/zyn3/mruby-zest-build/deps/mruby-nanovg/mrblib/context.rb:21:in Nanovg::Context.initialize
        [1] /root/zyn3/mruby-zest-build/src/mruby-widget-lib/mrblib/script.rb:185:in ZRunner.init_gl
/root/zyn3/mruby-zest-build/deps/mruby-nanovg/mrblib/context.rb:21: Could not create Context. (NVGError)
[FATAL ERROR] Mruby Is Unable To Continue
[INFO:Zyn] setup_pugl()
[INFO:Zyn] zest_tick()
[INFO:Zyn] zest_open()
[INFO:Zyn] Starting Zyn-Fusion
[INFO:Zyn] Thanks for supporting the developement of this project
[INFO:Zyn] Creating MRuby Interpreter...
[debug] parsing json file
[debug] json parsed succesfully
Shader shader/vert error:
0:1(10): error: GLSL ES 1.00 is not supported. Supported versions are: 1.10, and 1.20

make: *** [run] Error 1

**Comment by fundamental** [comment]
I'm pretty sure GLSL ES 1.00 is OpenGLES 2.0 (open GL version numbers get weird). If your system says that \#version 100 isn't valid, then in nanovg_gl.h it may be possible to change "\#version 100\n" to "\#version 110" or "\#version 120". If that doesn't work then it's starting to get to the territory of trying to sort out the renderer speed with nanovg outside of zest.

**Comment by ctag-fh-kiel** [comment]
Zest starts with those changes but unfortunately, the rendering speed is still same same slowness with 100% CPU :( attached another callgrind log from make callgrind. also the current build_config.rb 
Any directions how to test with pure nanovg? Thx again!

[callgrind.out.zip](https://github.com/mruby-zest/mruby-zest/files/1657433/callgrind.out.zip)

[build_config.zip](https://github.com/mruby-zest/mruby-zest/files/1657452/build_config.zip)

**Comment by fundamental** [comment]
At this point I'd recommend downloading https://github.com/memononen/nanovg then building it with premake/make. Once you have it built it should produce a OpenGL2, OpenGL3, OpenGLES2, and OpenGLES3 versions of their demo application. The demo application also has a framerate tracker graph built in. Hopefully one of those versions shows some different performance.

**Comment by ctag-fh-kiel** [comment]
Hello, back on this issue after some time. I switched to a raspberry pi 3 after all, to see if it is the HW platform. I compiled nanovg and run the GLES2 example, frame rate is at <1fps, so same behaviour as zynfusion. I guess the reason simply is GLES2 not powerful enough on these platforms :( too bad.
Or any more directions?

Happy easter :)

**Comment by ctag-fh-kiel** [comment]
Oops, quick update, did a sudo raspi-config and enabled the GPU kernel module, suddenly fps>30, wow, I guess on the path to success :)

**Comment by fundamental** [comment]
Excellent :)

**Comment by ctag-fh-kiel** [comment]
I think we are pretty close now, rendering performance on raspberry pi with XFCE is ok, rotary encoders and buttons, envelopes etc. seems to work, but there is no text shown...
This is when compiled straight with the GL2 settings (I didn't apply any of the items we discussed above, as the nanovg GL2 example worked just like the GLES2 example).

I have attached the console log file, the renderer errors seem to occur when I click various UI elements.
Any ideas?

So close now, thx...!
[log.txt](https://github.com/mruby-zest/mruby-zest/files/1866635/log.txt)

**Comment by ctag-fh-kiel** [comment]
Update: Also with GLES2 changes as mentioned above same issue: no text display and Error messages at runtime...

**Comment by ctag-fh-kiel** [comment]
Last update for today: **SUCCESS :)**

With the patches as above applied for GLES2 it works. I previously I forgot to untar the package before running the install script, duh...!

Tomorrow, I will check more functionality...

**Comment by ctag-fh-kiel** [comment]
Ok, I created a pull request for a modified build script. Check it out and merge it if useful...
