### ISSUE TITLE
Incorrect scaling

### ISSUE THREAD

**Issue by ghost** [mruby-zest/mruby-zest#32]
Zest displays small under HiDPI screen, but if I change window size, it immediately becomes larger, and, no scaling on ardour5.

Is there a way to change the zest dpi parameters globally?

Execute zyn-fusion, and do nothing
![snap](https://user-images.githubusercontent.com/19620324/73380426-ffdcac80-42fe-11ea-868f-1dae993c89ff.png)

After changing window size
![snap](https://user-images.githubusercontent.com/19620324/73380646-6235ad00-42ff-11ea-8eb1-59d95f0bf114.png)

Ardour5 vst plugin
![snap](https://user-images.githubusercontent.com/19620324/73380796-9d37e080-42ff-11ea-9527-70a4285b86a2.png)

**Comment by fundamental** [comment]
There is no global DPI setting. The zest GUI attempts to rescale based upon the window size and only that.
