### ISSUE TITLE
No fonts - need help

### ISSUE THREAD

**Issue by schnitzeltony** [mruby-zest/mruby-zest#9]
Hi,

Am using Openembedded/Yocto cross build system and managed to go through/adapt the build scripts and get zyn-fusion running on RaspberryPi3 (was a challenge - no Ruby experience - but that's a different story).

Standalone  ZynAddSubFx (or just zyn-fusion) opens without crashing an I see the beautiful new GUI. 

There is only a 'little' problem: There are no fonts inside of the window (If you are missing further let me know):

![zyn-fusion](https://user-images.githubusercontent.com/2571823/45578843-33db3d00-b884-11e8-928f-58e208925d5c.png)

To debug I start zyn-fusion only from console and get:

>[INFO:Zyn] setup_pugl()
>[INFO:Zyn] zest_tick()
>[INFO:Zyn] zest_open()
>[INFO:Zyn] Found Assets at /opt/zyn-fusion/
>[INFO:Zyn] Starting Zyn-Fusion
>[INFO:Zyn] Thanks for supporting the developement of this project
>[INFO:Zyn] Creating MRuby Interpreter...
>[debug] parsing json file
>[debug] json parsed succesfully
>Error 00000501 after create tex
>Time for a fast load is 18.626ms load(0.085) class(0.008) spawn(18.533)...
>making reverse graph[1091]<12.086 ms>
>[INFO:Zyn] zest_setup()
>[DEBUG:Zyn] setting up animation fps
>Error 00000502 after convex fill

In /opt/zyn-fusion/font the files entypo.ttf/Roboto-Bold.ttf/Roboto-Light.ttf/Roboto-Regular.ttf are installed.

* Are these the mentioned fonts files used by zyn-fusion?
* What can I do to get more information (log) to see what's going wrong - there is e.g there is some some GL::debug how to enable it?

Would love to get this working...

**Comment by fundamental** [comment]
See https://github.com/mruby-zest/mruby-zest/issues/2 and https://github.com/zynaddsubfx/zyn-fusion-build/pull/13 . Unless I'm mistaken this issue was resolved by the discussion and resulting pull request.

**Comment by schnitzeltony** [comment]
Moving to OpenGLES2 helped! Thanks so much for the pointer
